const gameHandbook = {
    mechanics: { title: "Механики", items: { "Погода": "Влияет на игру.", "Компас": "Меняет погоду.", "Игральная кость": "Бонус попыток/веса." } },
    bonuses: { title: "Бонусы", items: { "Катушка": "+1 попытка", "Ласты": "x2 улов", "Маска": "Удалить хлам", "Акваланг": "x3 вес лучшего улова", "Фильтр": "Защита попытки" } },
    debuffs: { title: "Дебафы", items: { "Чайка": "Стащит рыбу", "Утка": "Подменяет на хлам", "Рак": "Вес до 2.5кг" } }
};
const baseUrl = 'https://raw.githubusercontent.com/furbolog-hub/Fish_game/main/sounds/';
const sounds = { throw: new Audio(baseUrl + 'throw.ogg'), bonus: new Audio(baseUrl + 'bonus.ogg'), debuff: new Audio(baseUrl + 'debuff.ogg'), successfull: new Audio(baseUrl + 'successful.ogg'), achievement: new Audio(baseUrl + 'achievement.ogg'), legendary: new Audio(baseUrl + 'legendary.ogg'), unique: new Audio(baseUrl + 'unique.ogg') };
function playSound(s) { if (sounds[s]) { sounds[s].currentTime = 0; sounds[s].play().catch(e => console.log(e)); } }
let tg; try { tg = window.Telegram.WebApp; tg.ready(); tg.expand(); } catch (e) { tg = { HapticFeedback: { impactOccurred: () => {} } }; }
let state = { attempts: 3, catches: [], bonuses: { mask: false, aquaCount: 0, filter: false, fins: false }, activeDebuffs: [], weather: 'sunny', luckyFisher: false, bonusCount: 0, leviathanBonus: 0, hasMessageInBottle: false, hasCompass: false, diceMultiplier: 1, filtersUsed: 0, wasAttacked: false, transmutedCount: 0 };
const fishes = ["Палтус", "Палия", "Белый амур", "Щука", "Семга", "Солнечник", "Подкаменщик", "Сом", "Окунь", "Плотва", "Кижуч", "Семотилус", "Меланотения", "Горчак", "Жерех", "Ринихт", "Лосось", "Корюшка", "Судак", "Арктический голец", "Красноперка", "Золотая форель", "Фундулюс", "Озерный сиг", "Карпиодес"];
const trash = ["Старый башмак", "Спутанная леска", "Сломанный поплавок", "Ржавый крючок", "Половина блесны", "Размокший кусок бумаги"];
const legendaryItems = ["Чешуя Левиафана", "Послание в бутылке", "Компас потерянных глубин", "Запечатанный сундук"];
const uniqueItems = ["Глубоководное нечто", "Игральная кость"];
const icons = { "Палтус": "🐟", "Палия": "🐠", "Белый амур": "🐟", "Щука": "🦈", "Семга": "🍣", "Солнечник": "☀️", "Подкаменщик": "🐡", "Сом": "〰️", "Окунь": "🐟", "Плотва": "🐟", "Кижуч": "🐠", "Семотилус": "🐟", "Меланотения": "🌈", "Горчак": "🐟", "Жерех": "🐟", "Ринихт": "🐟", "Лосось": "🎣", "Корюшка": "🐟", "Судак": "🐟", "Арктический голец": "❄️", "Красноперка": "🎈", "Золотая форель": "✨", "Фундулюс": "🐟", "Озерный сиг": "🐟", "Карпиодес": "🐟", "Старый башмак": "👞", "Спутанная леска": "🧵", "Сломанный поплавок": "🪡", "Ржавый крючок": "🪝", "Половина блесны": "🪙", "Размокший кусок бумаги": "📄", "Чешуя Левиафана": "🐉", "Послание в бутылке": "📜", "Компас потерянных глубин": "🧭", "Запечатанный сундук": "📦", "Глубоководное нечто": "🐙", "Игральная кость": "🎲" };
function getWeightIcon(w) { if (w >= 20) return "👽"; if (w >= 10) return "🏆"; if (w >= 7.6) return "🥇"; if (w >= 4.6) return "🥈"; if (w > 0) return "🥉"; return ""; }
document.addEventListener('DOMContentLoaded', () => { document.getElementById('action-btn').addEventListener('click', startFishing); document.getElementById('handbook-btn').addEventListener('click', toggleHandbook); document.getElementById('weather-icon').onclick = toggleWeatherHelp; updateWeather(); setInterval(updateWeather, 7200000); updateUI(); });
function toggleHandbook() { const m = document.getElementById('handbook-modal'); if (m.classList.contains('hidden')) { renderHandbook(); m.classList.remove('hidden'); } else { m.classList.add('hidden'); } }
function renderHandbook() { const c = document.getElementById('handbook-data'); if (c.innerHTML !== "") return; let h = "<h1>Справочник рыбака</h1>"; for (let s in gameHandbook) { h += `<h2>${gameHandbook[s].title}</h2><ul>`; for (let k in gameHandbook[s].items) h += `<li><strong>${k}:</strong> ${gameHandbook[s].items[k]}</li>`; h += "</ul>"; } c.innerHTML = h; }
function toggleWeatherHelp() { const el = document.getElementById('weather-help'); const txt = { 'sunny': '☀️ Шанс атаки чайки!', 'rain': '🌧️ Утка (снижает вес)', 'calm': '🌊 Штиль: Бонусы!', 'storm': '🌪️ Шторм: Много хлама', 'fog': '🌫️ Легендарки выше!', 'eclipse': '🌑 Артефакты удвоены!', 'golden': '✨ +2кг к рыбе', 'thunder': '⚡ Гроза: риск молнии' }; let html = `<p>${txt[state.weather]}</p>`; if (state.hasCompass) html += `<button onclick="changeWeather()" class="fish-btn">Сменить погоду</button>`; document.getElementById('help-text').innerHTML = html; el.classList.remove('hidden'); }
function changeWeather() { updateWeather(); document.getElementById('weather-help').classList.add('hidden'); }
function updateWeather() { const weathers = ['sunny', 'rain', 'calm', 'storm', 'fog', 'eclipse', 'golden', 'thunder']; state.weather = weathers[Math.floor(Math.random() * weathers.length)]; document.getElementById('weather-icon').innerText = { 'sunny': '☀️', 'rain': '🌧️', 'calm': '🌊', 'storm': '🌪️', 'fog': '🌫️', 'eclipse': '🌑', 'golden': '✨', 'thunder': '⚡' }[state.weather]; }
function startFishing() { playSound('throw'); if (state.attempts <= 0) return; document.getElementById('action-btn').disabled = true; if (state.weather === 'thunder' && Math.random() < 0.2 && state.bonuses.aquaCount === 0) { alert("⚡ Молния!"); state.attempts--; updateUI(); document.getElementById('action-btn').disabled = false; return; } setTimeout(() => { let r = Math.random(); let lC = (state.weather === 'fog') ? 0.03 : 0.01; let uC = (state.weather === 'eclipse') ? 0.006 : 0.003; if (r < uC) { playSound('unique'); handleUnique(); } else if (r < lC) { playSound('legendary'); handleLegendary(); } else if (state.bonuses.mask) { catchFish(true); state.bonuses.mask = false; state.attempts--; } else if (r < ((state.weather === 'calm') ? 0.3 : 0.15)) { playSound('bonus'); handleBonus(); } else if (r < ((state.weather === 'storm' || state.weather === 'thunder') ? 0.7 : 0.4)) { logCatch(trash[Math.floor(Math.random() * trash.length)], 0, true, 'catch'); if (state.bonuses.filter) { state.bonuses.filter = false; state.filtersUsed++; } else state.attempts--; } else { catchFish(false); state.attempts--; } triggerDebuff(); updateUI(); renderHistory(); if (state.attempts === 0 && document.getElementById('modal').classList.contains('hidden')) endGame(); else document.getElementById('action-btn').disabled = false; }, 600); }
function handleUnique() { let u = uniqueItems[Math.floor(Math.random() * uniqueItems.length)]; logCatch(u, 0, false, 'unique'); alert("Артефакт: " + u); if (u === "Глубоководное нечто") { let c = 0; state.catches.forEach(f => { if (f.isTrash) { f.name = fishes[Math.floor(Math.random() * fishes.length)]; f.weight = parseFloat((20 + Math.random() * 10).toFixed(1)); f.isTrash = false; f.type = 'catch'; c++; } }); state.transmutedCount += c; } else showDiceModal(); }
function showDiceModal() { document.getElementById('action-btn').disabled = true; const m = document.getElementById('modal'); const l = document.getElementById('modal-fish-list'); l.innerHTML = '<h3>Игральная кость</h3>'; const b = document.createElement('button'); b.className = 'fish-btn'; b.innerText = "Бросить"; b.onclick = () => { let p = Math.floor(Math.random() * 6) + 1; l.innerHTML = `<p>Выпало: ${p}</p>`; const b1 = document.createElement('button'); b1.className = 'fish-btn'; b1.innerText = `+${p} попыток`; b1.onclick = () => { state.attempts += p; closeDice(); }; const b2 = document.createElement('button'); b2.className = 'fish-btn'; b2.innerText = `Множитель x${(1 + (p * 0.1)).toFixed(1)}`; b2.onclick = () => { state.diceMultiplier = (1 + (p * 0.1)); closeDice(); }; l.appendChild(b1); l.appendChild(b2); }; l.appendChild(b); m.classList.remove('hidden'); }
function closeDice() { document.getElementById('modal').classList.add('hidden'); document.getElementById('action-btn').disabled = false; updateUI(); }
function handleLegendary() { let i = legendaryItems[Math.floor(Math.random() * legendaryItems.length)]; logCatch(i, 0, false, 'legendary'); if (i === "Чешуя Левиафана") { state.attempts += 5; state.leviathanBonus = 2.0; alert("Чешуя Левиафана!"); } else if (i === "Послание в бутылке") state.hasMessageInBottle = true; else if (i === "Компас потерянных глубин") state.hasCompass = true; else if (i === "Запечатанный сундук") { for (let k = 0; k < 4; k++) catchFish(false, true); } }
function catchFish(m, c = false) { let iD = state.activeDebuffs.some(d => d.includes("Утка")); let iR = state.activeDebuffs.some(d => d.includes("Рак")); let n = fishes[Math.floor(Math.random() * fishes.length)]; let w; if (iD) { if (Math.random() < 0.5) { n = trash[Math.floor(Math.random() * trash.length)]; w = 0; } else w = parseFloat((0.1 + Math.random() * 0.4).toFixed(1)); } else if (m) w = parseFloat((6.5 + Math.random() * 3.4).toFixed(1)); else if (Math.random() < 0.05) { w = parseFloat((10.0 + Math.random() * 5.0).toFixed(1)); state.luckyFisher = true; } else w = parseFloat((0.1 + Math.random() * 6.4).toFixed(1)); if (state.weather === 'golden') w += 2.0; w += state.leviathanBonus; let bW = 0; if (iR) { if (w > 2.5) w = 2.5; if (state.hasMessageInBottle) { w += 2.5; bW = 2.5; } } if (w >= 10.0) playSound('successfull'); logCatch(n, w, (w === 0), 'catch', false, bW, c); document.getElementById('message').innerText = `Поймал: ${n} (${w.toFixed(1)} кг)`; }
function handleBonus() { state.bonusCount++; let b = Math.random(); if (b < 0.2) { logCatch("Бонус: Катушка (+1)", 0, true, 'bonus'); state.attempts++; } else if (b < 0.4) { state.bonuses.fins = true; logCatch("Бонус: Ласты (x2)", 0, true, 'bonus'); } else if (b < 0.6) { state.bonuses.mask = true; showModal(); logCatch("Бонус: Маска", 0, true, 'bonus'); } else if (b < 0.8) { state.bonuses.aquaCount++; logCatch("Бонус: Акваланг", 0, true, 'bonus'); } else { state.bonuses.filter = true; logCatch("Бонус: Фильтр", 0, true, 'bonus'); } }
function triggerDebuff() { if (state.weather === 'storm' || state.weather === 'thunder' || Math.random() > 0.25) return; let t = Math.random(); let txt = ""; if (t < 0.33 && state.weather === 'calm') txt = "Дебаф: Рак (вес до 2.5кг)"; else if (t < 0.66 && state.weather === 'sunny') { let f = state.catches.find(c => !c.isTrash && !c.isStolen && c.type === 'catch'); if (f) { f.isStolen = true; txt = "Дебаф: Чайка стащила рыбу!"; state.wasAttacked = true; } } else if (state.weather === 'rain') { txt = "Дебаф: Утка (малый вес/хлам)"; state.wasAttacked = true; } if (txt && !state.activeDebuffs.includes(txt)) { playSound('debuff'); state.activeDebuffs.push(txt); logCatch(txt, 0, true, 'debuff'); } }
function logCatch(n, w, iT, t, iR = false, bW = 0, iFC = false) { state.catches.push({ name: n, weight: w, isTrash: iT, type: t, isStolen: false, isRemoved: iR, bonusWeight: bW, isFromChest: iFC }); }
function renderHistory() { const list = document.getElementById('history-list'); list.innerHTML = ''; state.catches.forEach(c => { const li = document.createElement('li'); const icon = icons[c.name] || "🎣"; if (c.isRemoved) li.style.textDecoration = "line-through"; else if (c.isStolen) li.className = 'strikethrough'; else { if (c.type === 'bonus') li.className = 'log-bonus'; else if (c.type === 'debuff') li.className = 'log-debuff'; else if (c.isTrash) li.className = 'log-trash'; else if (uniqueItems.includes(c.name)) li.className = 'log-unique'; else if (legendaryItems.includes(c.name)) li.className = 'log-legendary'; } li.innerHTML = `${c.isFromChest ? "📦 " : ""}${icon} ${c.name} ${c.weight > 0 ? c.weight.toFixed(1)+' кг' : ''} ${c.bonusWeight > 0 ? `<span style="color:#ff00ff">(+${c.bonusWeight.toFixed(1)}кг)</span>` : ''}`; list.appendChild(li); }); }
function updateUI() { let s = state.catches.filter(c => !c.isRemoved && (c.type !== 'catch' || !c.isStolen || state.hasMessageInBottle)).reduce((a, c) => a + c.weight, 0); document.getElementById('score').innerText = `Улов: ${(s * state.diceMultiplier).toFixed(1)} кг | Попыток: ${state.attempts}`; }
function endGame() { let v = state.catches.filter(c => !c.isRemoved && (c.type !== 'catch' || !c.isStolen || state.hasMessageInBottle) && c.weight > 0); let tot = v.reduce((a, c) => a + c.weight, 0) * state.diceMultiplier; if (state.bonuses.fins) tot *= 2; let achs = []; if (state.luckyFisher) achs.push("🏆 Удачливый рыбак"); if (state.bonusCount >= 3) achs.push("✨ Любимчик Фортуны"); if (v.length > 0 && v.every(c => c.weight >= 10.0)) achs.push("🦈 Акула бизнеса"); if (state.transmutedCount >= 5) achs.push("🔬 Трансмутатор"); if (!state.wasAttacked && state.catches.length > 5) achs.push("🛡️ Неуловимый"); if (tot >= 500) achs.push("🐘 Тяжеловес"); if (achs.length > 0) playSound('achievement'); document.getElementById('final-result').innerHTML = `<strong>Итог: ${tot.toFixed(2)} кг</strong><div style="margin-top:10px;">${achs.join('<br>')}</div><div style="margin-top:10px;">${new Date().toLocaleDateString()} | ${new Date().toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}</div>`; document.getElementById('final-result').classList.remove('hidden'); }
